export type Locale = 'en' | 'zh'

export const strings: Record<Locale, Record<string, string>> = {
	en: {
		tabs_localMusic: 'Local Music',
		tabs_explore: 'Explore',
		tabs_settings: 'Settings',
		songs_search_placeholder: 'Search local songs',
		songs_loading: 'Loading local songs...',
		explore_search_placeholder: 'Search songs',
		explore_placeholder_title: 'Explore Apple Music songs',
		explore_placeholder_body: 'Search for songs to preview tracks and start playback instantly.',
		explore_searching: 'Searching Apple catalog...',
		explore_songs_section: 'Songs',
		explore_unknown_album: 'Unknown album',
		explore_no_songs: 'No songs found',
		explore_no_results: 'No results',
		settings_language: 'Language',
		settings_language_description: 'Choose your preferred language',
		settings_theme: 'Theme',
		settings_theme_description: 'Light, Dark or follow system',
		settings_search_placeholder: 'Search settings',
		settings_no_results: 'No settings matched your search.',
		settings_follow_system: 'Follow system',
		settings_english: 'English',
		settings_chinese: '中文',
		settings_system_theme: 'System default',
		settings_light_theme: 'Light theme',
		settings_dark_theme: 'Dark theme',
		settings_dark_mode: 'Dark mode',
		settings_dark_mode_helper: 'Toggle dark theme quickly',
		queue_play: 'Play',
		queue_shuffle: 'Shuffle',
	},
	zh: {
		tabs_localMusic: '本地音乐',
		tabs_explore: '发现',
		tabs_settings: '设置',
		songs_search_placeholder: '搜索本地歌曲',
		songs_loading: '正在加载本地歌曲...',
		explore_search_placeholder: '搜索歌曲',
		explore_placeholder_title: '探索 Apple Music 歌曲',
		explore_placeholder_body: '搜索歌曲来试听并立即播放。',
		explore_searching: '正在搜索 Apple 曲库...',
		explore_songs_section: '歌曲',
		explore_unknown_album: '未知专辑',
		explore_no_songs: '没有找到歌曲',
		explore_no_results: '没有结果',
		settings_language: '语言',
		settings_language_description: '选择你的偏好语言',
		settings_theme: '主题',
		settings_theme_description: '浅色、深色或跟随系统',
		settings_search_placeholder: '搜索设置',
		settings_no_results: '没有匹配的设置。',
		settings_follow_system: '跟随系统',
		settings_english: '英文',
		settings_chinese: '中文',
		settings_system_theme: '系统默认',
		settings_light_theme: '浅色主题',
		settings_dark_theme: '深色主题',
		settings_dark_mode: '深色模式',
		settings_dark_mode_helper: '快速切换深色主题',
		queue_play: '播放',
		queue_shuffle: '随机播放',
	},
}
