export type Locale = "en" | "zh";

export const strings: Record<Locale, Record<string, string>> = {
	en: {
		tabs_home: "Home",
		tabs_localMusic: "Music",
		tabs_explore: "Explore",
		tabs_recommend: "Recommend",
		tabs_favorites: "Favorites",
		tabs_recently: "Recently",
		tabs_settings: "Settings",
		songs_search_placeholder: "Search local songs",
		songs_loading: "Loading local songs...",
		explore_search_placeholder: "Search songs",
		explore_placeholder_title: "Explore Apple Music songs",
		explore_placeholder_body: "Search for songs to preview tracks and start playback instantly.",
		explore_searching: "Searching Apple catalog...",
		explore_songs_section: "Songs",
		explore_unknown_album: "Unknown album",
		explore_no_songs: "No songs found",
		explore_no_results: "No results",
		explore_quick_filters: "Jump into a mood",
		explore_curated_title: "Spotlight scenes",
		explore_curated_caption: "Short journeys you can queue in seconds",
		explore_cta_surprise: "Surprise me",
		explore_cta_focus: "Focus mode",
		explore_trending: "Trending",
		settings_language: "Language",
		settings_language_description: "Choose your preferred language",
		settings_theme: "Theme",
		settings_theme_description: "Light, Dark or follow system",
		settings_accent: "Accent color",
		settings_accent_description: "Control the foreground color used across the app",
		settings_search_placeholder: "Search settings",
		settings_no_results: "No settings matched your search.",
		settings_follow_system: "Follow system",
		settings_english: "English",
		settings_chinese: "中文",
		settings_system_theme: "System default",
		settings_light_theme: "Light theme",
		settings_dark_theme: "Dark theme",
		settings_dark_mode: "Dark mode",
		settings_dark_mode_helper: "Toggle dark theme quickly",
		settings_accent_apple_music: "Apple Music pink",
		settings_accent_apple_music_helper: "Default accent",
		settings_accent_ocean_blue: "Ocean blue",
		settings_accent_ocean_blue_helper: "Bright and clean",
		settings_accent_mint: "Mint green",
		settings_accent_mint_helper: "Soft, refreshing",
		settings_accent_sunset: "Sunset orange",
		settings_accent_sunset_helper: "Warm highlight",
		settings_about: "About",
		settings_about_description: "Project information and links",
		settings_github: "GitHub",
		settings_github_helper: "Author Super1Windcloud",
		musicfeed_loading: "Tuning up your mix...",
		musicfeed_error: "Unable to load tracks right now.",
		musicfeed_retry: "Tap to retry",
		musicfeed_empty: "No tracks yet. Try refreshing.",
		musicfeed_recommend_title: "Tailored picks for you",
		musicfeed_recommend_subtitle: "Handpicked moods powered by MusicAPI",
		musicfeed_favorites_title: "Favorites",
		musicfeed_favorites_subtitle: "Loved by the community, ready to vibe",
		musicfeed_recently_title: "Recently",
		musicfeed_recently_subtitle: "Fresh drops and late-night spins",
		queue_play: "Play",
		queue_shuffle: "Shuffle",
		home_title: "NetEase-inspired home",
		home_subtitle: "Daily mixes, liked picks, and your latest spins in one feed.",
		home_action_recommend: "Daily Mix",
		home_action_favorites: "Liked",
		home_action_recent: "Recent",
		home_section_recommend: "Tailored picks",
		home_section_favorites: "Community favorites",
		home_section_recent: "Freshly played",
		home_refresh: "Refresh",
		home_empty: "Nothing to play here yet.",
	},
	zh: {
		tabs_home: "首页",
		tabs_localMusic: "音乐",
		tabs_explore: "发现",
		tabs_recommend: "推荐",
		tabs_favorites: "收藏",
		tabs_recently: "最近",
		tabs_settings: "设置",
		songs_search_placeholder: "搜索本地歌曲",
		songs_loading: "正在加载本地歌曲...",
		explore_search_placeholder: "搜索歌曲",
		explore_placeholder_title: "探索 Apple Music 歌曲",
		explore_placeholder_body: "搜索歌曲来试听并立即播放。",
		explore_searching: "正在搜索 Apple 曲库...",
		explore_songs_section: "歌曲",
		explore_unknown_album: "未知专辑",
		explore_no_songs: "没有找到歌曲",
		explore_no_results: "没有结果",
		explore_quick_filters: "氛围快选",
		explore_curated_title: "精选场景",
		explore_curated_caption: "一键排队的小旅程",
		explore_cta_surprise: "来点惊喜",
		explore_cta_focus: "专注模式",
		explore_trending: "热搜",
		settings_language: "语言",
		settings_language_description: "选择你的偏好语言",
		settings_theme: "主题",
		settings_theme_description: "浅色、深色或跟随系统",
		settings_accent: "前景色",
		settings_accent_description: "控制应用内使用的主题前景色",
		settings_search_placeholder: "搜索设置",
		settings_no_results: "没有匹配的设置。",
		settings_follow_system: "跟随系统",
		settings_english: "英文",
		settings_chinese: "中文",
		settings_system_theme: "系统默认",
		settings_light_theme: "浅色主题",
		settings_dark_theme: "深色主题",
		settings_dark_mode: "深色模式",
		settings_dark_mode_helper: "快速切换深色主题",
		settings_accent_apple_music: "Apple Music 粉",
		settings_accent_apple_music_helper: "默认前景色",
		settings_accent_ocean_blue: "海洋蓝",
		settings_accent_ocean_blue_helper: "明亮、干净",
		settings_accent_mint: "薄荷绿",
		settings_accent_mint_helper: "柔和清新",
		settings_accent_sunset: "落日橙",
		settings_accent_sunset_helper: "温暖高亮",
		settings_about: "关于",
		settings_about_description: "项目信息与链接",
		settings_github: "GitHub",
		settings_github_helper: "作者 Super1Windcloud",
		musicfeed_loading: "正在为你调音...",
		musicfeed_error: "当前无法获取歌曲。",
		musicfeed_retry: "点击重试",
		musicfeed_empty: "暂无歌曲，试试刷新",
		musicfeed_recommend_title: "为你推荐",
		musicfeed_recommend_subtitle: "由 MusicAPI 精选的氛围歌单",
		musicfeed_favorites_title: "收藏精选",
		musicfeed_favorites_subtitle: "人气之选，随时开听",
		musicfeed_recently_title: "最近发现",
		musicfeed_recently_subtitle: "全新发布与最新热听",
		queue_play: "播放",
		queue_shuffle: "随机播放",
		home_title: "网易云式首页",
		home_subtitle: "每日推荐、精选收藏与最近播放，一屏尽览。",
		home_action_recommend: "每日推荐",
		home_action_favorites: "我的收藏",
		home_action_recent: "最近播放",
		home_section_recommend: "个性推荐",
		home_section_favorites: "精选收藏",
		home_section_recent: "新鲜足迹",
		home_refresh: "刷新",
		home_empty: "这里还没有可播的内容",
	},
};
